# Generated by Django 2.1.7 on 2019-03-06 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('data', models.TextField(default='')),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
